### ISSUE TITLE
Compatibility for Haema and Bewitchment

### ISSUE THREAD

**Issue by Lukebb04** [Luke100000/minecraft-comes-alive#108]
can you make villagers for these?
[Haema](https://www.curseforge.com/minecraft/mc-mods/haema) adds a vampire hunter
[Bewitchment](https://www.curseforge.com/minecraft/mc-mods/bewitchment) adds a vampire

**Comment by Luke100000** [comment]
Sounds like plugin ideas for me.
The Vampire hunters may be reworked Illagers similar to bounty hunters in mca, in which case support may be granted automatically.

**Comment by CDAGaming** [comment]
7.3.x contains the config settings to allow modded villagers to attempt to auto-convert to MCA, though this just results in a normal villager, due to very different nbt. note this will fail if that villager does not extend off a base villagerentity.

Anything further will need a plugin, which is out of scope for here.
