### ISSUE TITLE
Have following villagers teleport to the follower if they got too far away

### ISSUE THREAD

**Issue by pantsguyapp** [Luke100000/minecraft-comes-alive#130]
Similar to tamed animals.

**Comment by WildBamaBoy** [comment]
Of course, this was present in the original.

**Comment by CDAGaming** [comment]
@pantsguyapp @WildBamaBoy This was removed in 7.2 explicitly due to the unsafe nature of it. When combined with their greeting ai, it let to very catastrophic results, often resulting in the villager getting killed out of frame. While the task itself was improved to prevent unsafe locations, I leave this one up to @Luke100000 if they wish to re-add this back in for 7.2

**Comment by Luke100000** [comment]
It was only disabled, not removed, so if we spent some hours making sure no bugs are left we can re enable this. In theory the AI should be secure, yet we have a lot of mysterious events happening :D

**Comment by CDAGaming** [comment]
Indeed, and this was the reasoning i added a new method to the task, so conditions that dictate a safe teleport can be defined. At the moment though, there is only a light level check to prevent underground teleports

**Comment by CDAGaming** [comment]
Closed, re-implemented and configurable in 7.2.0
