### ISSUE TITLE
Crash upon entering world [1.18.2]

### ISSUE THREAD

**Issue by CuteNeko-Chan** [Luke100000/minecraft-comes-alive#164]
Game crashes when trying to load a world.

version 7.2.0 rc1
Log:
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/8447716/latest.log)

**Comment by CDAGaming** [comment]
Please retry in rc2. There is also a chance that errors from other mods may be causing issues for MCA as well.

**Comment by CDAGaming** [comment]
```
[02:47:28] [Worker-Main-2/ERROR]: 
***************************************
Failed to get mob. Please check that repurposed_structures:dungeons/deep.json is correct or that no other mod is interfering with how vanilla reads data folders. Let TelepathicGrunt know about this too!
***************************************
```

For instance, several of your mods are also throwing errors from something that may be modifying how data folders are read (Which is how MCA gets it's naming tables). For this reason, I'm going to close this issue as a potential mod conflict, though you are free to re-open this if this issue is present with just MCA
