### ISSUE TITLE
Player Marriage still buggy as hell

### ISSUE THREAD

**Issue by Luke100000** [Luke100000/minecraft-comes-alive#217]

**Comment by CrystalRiver998** [comment]
Player marriage issues-
can marry, but when you both log out and log back in you are no longer married. 1.16.5 and 1.18.2

**Comment by Niphoria** [comment]
can confirm - i personally dont even have to log out for it to no longer work - it just throws an error at me when i accept

**Comment by Luke100000** [comment]
Please send me the error, because I was not referring to an error so thats new XD

**Comment by Niphoria** [comment]
When i hit "/mca accept %playername%"
i get an error of "An unexpected error occurred trying to execute that command"
meanwhile on his end it he gets the message of it working
however if i try "/mca procreate" i will get an error of telling me "Your spouse is not present on the server"
if trying to marry again i get the error "You cannot send a proposal since you are already married."

i would send log files - but they only log the chat (server and client) and there are no errors or anything - does MCA-Reborn create other log files i should be aware of ?

Oh and we are running 1.18.2 with fabric 0.14.8

and we didnt die in between

**Comment by Luke100000** [comment]
Sadly no, minecraft hides the actual error in commands... MCA 7.3.4 has a cleanup related to relationships, maybe it fixes the issue. Probably not tho

**Comment by Niphoria** [comment]
I will update once the version comes out and i tested it

**Comment by CrystalRiver998** [comment]
have not noticed an issue with player marriage since the latest update. haven't tried using the commands again but it still says we are married in the mca player menu and our kids family trees arent messed up, like they were previously. never had an issue with us proposing.

**Comment by CDAGaming** [comment]
Closed as presumed fixed, feel free to re-open if this re-appears
