### ISSUE TITLE
On Rose Gold Book Spawn

### ISSUE THREAD

**Issue by Gamerbolts** [Luke100000/minecraft-comes-alive#244]
Hello! I am creating a modpack and I want the players to spawn with specific items and the On Rose Gold book spawns. Is there a way to stop the book from spawning with the player? I can't find anything in the config.

**Comment by Luke100000** [comment]
I have two possible fixes in mind: you can either modify the loot table `books/rose_gold`  to be empty, or modify the achievement `recipes/misc/rose_gold_ingot_smelting` to not grant a reward.
But the spawning of the book was a bug anyways so that's fixed in the next version, thanks for reporting :)
