### ISSUE TITLE
The Github Link Is Always Broken.

### ISSUE THREAD

**Issue by KingMushroomBoy** [Luke100000/minecraft-comes-alive#305]
I found out how to check the new updates though.

**Comment by CDAGaming** [comment]
.9 and .10 were primarily bug-fixes and reinstating 1.19 support

**Comment by Luke100000** [comment]
Link not fixed yet

**Comment by CDAGaming** [comment]
@Luke100000 You have been told of this before. The link being broken is due to the + sign not being recognized on CurseForge's end (https://github.com/Luke100000/minecraft-comes-alive/blob/7.3.10+1.19/changelog.md) <-- This link works since the + is recognized properly.

Closing as not our issue, it is Curseforge's issue to deal with and has been for months.

**Comment by Luke100000** [comment]
It doesn't matter whose issue it is, its not working and that's the problem. And the fix isn't really hard either.

**Comment by CDAGaming** [comment]
Yes, but there is nothing we can do to fix that.

**Comment by CDAGaming** [comment]
We cant change how versions are done, as that's how it is required by Reckon, unless we wish to ditch one of the two versions we support (Meaning either 1.18.2 or 1.19 gets dropped).

Only other solution is to contact CurseForge to resolve this.

**Comment by Luke100000** [comment]
It was literally just a typo in my CI script, I assumed an - instead of +
