### ISSUE TITLE
1.18.2 missing editor options

### ISSUE THREAD

**Issue by 78codemonkey** [Luke100000/minecraft-comes-alive#387]
MC1.18.2, FORGE 40.1.79, MCA 7.3.21
all dependencies at latest versions/release

Issue: options for Villager, Player, and Vanilla are not being shown

Explanation: (Note-- it works in my old pack)
I made new pack similar to my old one, but the only changes was:
->Instead of Optifine, I used "forge sodium and all addons including dynamic lights"
->Instead of Conquest resource pack, I used Stoneborn resource pack and create compact resource pack
->Added "Twilight, twilight paintings, and twilight delights"
->Added "forge Beadspreads"
->Added "Building Gadget"
->Added "Camera mod"
->Added "Epic Fight and epic fight NBT"
->Added "Extra Golems"
->Added "Feature NBT Deadlock Be Gone"
->Added "Guard Villagers"
->Added "Goblins & Dungeons"
->Added "forge Immersive Portals"
->Added "SecurityCraft"
Currently using Adaptive performance mod and all addons and some performance mods by "someaddon", though I have them in old pack where mca is working 100%. So the major mod changes are Twilight, No optifine but sodium(forge), and mods with nbt in their name.

**Comment by CDAGaming** [comment]
This is due to a change in 7.3.21, via the `playerRenderBlacklist`, which disables those options you mentioned
![image](https://user-images.githubusercontent.com/16328918/189414153-d9b1b35b-05ee-4117-afc9-ebfeabd75ce9.png)
Ref: https://github.com/Luke100000/minecraft-comes-alive/wiki/Config

Your free to remove that line from the config, but there is good reason that it is there.

**Comment by 78codemonkey** [comment]
Sorry, wasn't asking for fixing, was wondering which mod was causing. Thanks for the respond and config details :)
p.s. I know epic fight isn't friendly with models outside of vanilla, that's why I didn't add werewolves addon for vampirism
