### ISSUE TITLE
crafting problem

### ISSUE THREAD

**Issue by An059** [Luke100000/minecraft-comes-alive#40]
i can only craft rings and nothing else like whistle and tombstone , am using Tlauncher 1.16.5 forge version 36.2.19,  mca reborn 7.0.4-forge

**Comment by Luke100000** [comment]
I can confirm that recipes do not show up in the recipe book. However, I can craft them. Can you verify on e.g. the blueprint: https://minecraft-comes-alive-reborn.fandom.com/wiki/Blueprint?

**Comment by An059** [comment]
yep i can craft it. I think that am confused because of the old update, I did not find any site related to the new update, only the download page*

**but i can't find the way to craft the tombstone, its not in the items list and am using the old way can u help with that ?**

![5732748](https://user-images.githubusercontent.com/95773659/145375794-6e65158a-9e24-48b3-88b2-8385839e4261.png)

**Comment by Luke100000** [comment]
Yes, that recipe is outdated, we use a gold block now. The tombstone you know doesn't even exist anymore too, so make sure to take a look at the (not working) recipe book XD I'm on it, should be fixed in 7.0.5. Alternatively, you can join our discord https://discord.gg/8NfqyDFr and bother our Wiki authors to add all recipes :)

**Comment by An059** [comment]
ok thank you 👌
