### ISSUE TITLE
Eldritch Arcane Workings incompatible

### ISSUE THREAD

**Issue by Gamerbolts** [Luke100000/minecraft-comes-alive#447]
Hello! I am creating a modpack and was flying around my test world testing. I got a crash, here if the crashlog and log. Any help is appreciated. Thank you!

[crash-2022-11-02_09.13.52-server.txt](https://github.com/Luke100000/minecraft-comes-alive/files/9921134/crash-2022-11-02_09.13.52-server.txt)
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/9921135/latest.log)

**Comment by Gamerbolts** [comment]
Sorry this is for the Fabric version

**Comment by Gamerbolts** [comment]
Is there any update on this? I keep crashing so had to remove it from the pack :(

**Comment by Luke100000** [comment]
Sadly not, and I doubt its directly related to MCA.
For context: the mca villager updates it's inventory, and it has an item in it with a custom update method. That update method (which is not part of vanilla or mca) assumed the holder is a PlayerEntity (or at least I think class_1657 is a PlayerEntity based on a quick google, and it kinda makes sense).
That means, you have to find the mod implementing that broken item. But it gets more complicated: Your crashlog luckily contains the inventory. And it only contains wheat and seeds. So that means someone tinkered with inbuild methods. Maybe some farming or food related mod?
If you have time you can manually search for the mod. At `580.46, 67.94, 131.31` is the entity causing the issue. You can remove mods and see of it still happens, or remove everything except mca to test if it is indeed a mca issue. Only do this on a world copy!

**Comment by Gamerbolts** [comment]
Thanks for the reply. Ok I will do that and see if I can pinpoint the issue. Ty!

**Comment by Gamerbolts** [comment]
After working on it for awhile I have it narrowed down, still going to see if I can pinpoint it, really hard though because it is not crashing all the time.
![image](https://user-images.githubusercontent.com/20451601/208195090-cd6119f1-6e4e-4d79-bc39-790ccc607035.png)

**Comment by Gamerbolts** [comment]
ok I have found the mod! It is Eldritch Arcane Workings v1.0.4

Here is the log and crashlog with Just MCA, Architectury API, Fabric API and Eldritch Arcane Workings
[crash-2022-12-16_16.22.10-server.txt](https://github.com/Luke100000/minecraft-comes-alive/files/10249748/crash-2022-12-16_16.22.10-server.txt)

[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/10249750/latest.log)

I'll post over at the Eldritch Arcane Workings github but I am not too sure what to say, they will see the log and say it's your mod causing issues. Thanks for the help!

**Comment by Luke100000** [comment]
> ok I have found the mod! It is Eldritch Arcane Workings v1.0.4
> 
> Here is the log and crashlog with Just MCA, Architectury API, Fabric API and Eldritch Arcane Workings [crash-2022-12-16_16.22.10-server.txt](https://github.com/Luke100000/minecraft-comes-alive/files/10249748/crash-2022-12-16_16.22.10-server.txt)
> 
> [latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/10249750/latest.log)
> 
> I'll post over at the Eldritch Arcane Workings github but I am not too sure what to say, they will see the log and say it's your mod causing issues. Thanks for the help!

Awesome work! I took a look into the source and it is indeed this mixin here performing an unsafe cast: https://github.com/ZuzAser80/EldritchArcaneWorkings/blob/1.19/src/main/java/net/fabricmc/eaw/mixin/rune_support/ItemInject.java
Just link that file and mention the cast :)

**Comment by Gamerbolts** [comment]
Thanks! Took awhile but was worth it to find the issue now I just hope the other mod author fixes it. Thanks for the help. I'll close this now.
