### ISSUE TITLE
The MCA People Stopped Picking Up Bread?

### ISSUE THREAD

**Issue by Mewcenary** [Luke100000/minecraft-comes-alive#53]
For some weird reason, the MCA's are not picking up the bread anymore.  Even the new spawns and the Spawn-Egg spawns.  They look down at it, but can't pick it up-- the same with wheat seeds and other items villagers can pick up.  Not being able to sleep happened at the same time, not sure if the two are connected.  When night happens you can't sleep, so I have to keep resetting the day lol.  

Server
Forge:  1.16.5 - 36.2.23
MCA Reborn 7.0.4 
![2022-01-19_00 43 55](https://user-images.githubusercontent.com/85654348/150088560-e0dd624b-4c26-4a3f-8271-797732400865.png)

**Comment by Luke100000** [comment]
Can you verify that the inventory is not full? E.g. by testing this behavior on your family.
To clarify, is the player (you) unable to sleep or the villagers? What happens if you do so? Error msg, or nothing? In case nothing happens, maybe append the log.

While there are no such bugs reported yet (and most likely not fixed), it's always a good idea to use the newest mca version too before reporting a bug.

The unreleased 7.0.7 fixes an inventory duplicating bug so this may be related, therefore the inventory check.

**Comment by Mewcenary** [comment]
Aaah, yeah I think that is the issue.  I made a husband, gave him bread, he picked up 1, but can't pick up the others, and his inventory is empty.  The other issues I was able to resolve were by resetting the server. No idea what went wrong, no game crash report.

![2022-01-19_02 00 54](https://user-images.githubusercontent.com/85654348/150098541-526f1e85-10d1-4453-bddf-6b316582596f.png)

**Comment by Luke100000** [comment]
Ok, thanks for the hints, I'll investigate the pickup issue.

The sleep issue is most likely not related to mca

**Comment by Mewcenary** [comment]
Update: Even after updating it to the 1.16.5/7.0.6 that you have available, they still can't pick bread/items up.

**Comment by Luke100000** [comment]
I am not able to reconstruct the issue. Can you please verify that mobgriefing is enabled (as disabling this would prevent pickup).
Can you also check if villagers move onto the item? So I can limit the issue to picking up.

**Comment by CDAGaming** [comment]
Closed due to non-response and not present in 7.2.0
