### ISSUE TITLE
MCA's congregate in the middle of nowhere

### ISSUE THREAD

**Issue by Mewcenary** [Luke100000/minecraft-comes-alive#54]
Not sure what's going on, but the MCA villagers are congregating at this one spot.  I've broken all nearby bells except their village bell, the same goes with the underground village (Stoneholm mod) and I've placed adequate beds, but they still go to this spot every night.  I'm not sure what to do.  This has been going on for a few days, I've tried everything that I can think of to do :/

![2022-01-19_20 46 10](https://user-images.githubusercontent.com/85654348/150270417-3d2926a5-e66d-43ce-a47e-8cfd5b08dfa4.png)
![2022-01-19_20 51 43](https://user-images.githubusercontent.com/85654348/150270450-9becab41-33c0-4edc-90dc-a89f1406433f.png)

These are the Mods I use
![Mod List](https://user-images.githubusercontent.com/85654348/150271186-0a19dfd1-6ff4-436e-8fe9-6ae303427d48.png)

**Comment by Luke100000** [comment]
This is creepy ouf
If you want you can zip the entire game/server folder (+mods and everything) and upload it here: https://mega.nz/megadrop/iiXE0lz8qqU and I'll take a closer look at it.

**Comment by Mewcenary** [comment]
Maybe I am blind, but it is not giving me the option to download it.  Sorry for the late reply.  I will get it to you when I can.

**Comment by Mewcenary** [comment]
Ugh finally.  Okay, uploading now.  Hopefully, this works and I did it right x.x

Update:  the MCA villagers also travel LONG distances to other villages... and they somehow marry other villagers in other villages, even though they are 1000 blocks away (give or take).  They somehow morph into dirt etc.  When I log in, they teleport to me to greet me, which causes them to get hurt or die lol.  But, they do not greet my friend who is also a OP/Admin/Owner.
![2022-01-23_05 00 19](https://user-images.githubusercontent.com/85654348/150681424-6b3e8020-59a6-45c4-818b-e7c7af2828f4.png)

He traveled to this area and kept pacing around, and there was nothing there for him
![2022-01-23_05 42 57](https://user-images.githubusercontent.com/85654348/150681452-451a4073-0966-4020-a8cc-b45ebe0e057b.png)

**Comment by Luke100000** [comment]
Hi, I finally had time to tackle that issue. Your mysterious gathering spot is most likely the buggy remaining of the bell. I can not imagine that this is a mca-related issue since bell and meeting stuff should be vanilla. When I logged in, they did the same thing, but after that, I was not able to repeat that. That means I have no idea why it failed. It also appeared in the blueprint (which is just an icon). I increased the scan range from 8 to 32 blocks to avoid dead icons in the future.

Marrying other villagers from other villages might be a bug caused by earlier versions, where villages grew and grew and become so large that they covered half of the world. Maybe it's related to that because marrying across villages is technically impossible.

Greeting needs an overhaul I guess :)

The glitching is weird but I have no idea how this could happen.

The lonely wanderer is also a mystery, however, I wasn't able to reconstruct his behavior, so I wasn't able to test that.
