### ISSUE TITLE
[Fabric - MC 1.18.2 - MCA 7.4.0] Beds in removed or restricted buildings still count toward town max population.

### ISSUE THREAD

**Issue by Wilevar** [Luke100000/minecraft-comes-alive#554]
**Describe the bug**
Beds in removed or restricted buildings still count toward town max population.
Problem persists if beds are broken and replaced while building is removed or restricted.
Removing the building or making it restricted doesn't remove the beds from the town.

Additionally, villagers still sleep in beds in restricted buildings.

**To Reproduce**
1. Make any building containing a bed restricted, and observe that the village max population does not decrease.
2. Remove said building from the town via the blueprint, and see that the village max population remains unchanged.
3. Break down beds in said building, watch the village max population decrease accordingly.
4. Replace the beds even though the building is not a part of the village or is restricted, and see that the max population increases per bed.

**Version**
MCA 7.4.0, Minecraft 1.18.2, Modloader Fabric 0.14.13

**Comment by ncottrill** [comment]
I, too, have this problem. I deleted a building in order to try to reset the housing (remove villagers from the beds). (I've tried everything else in order to move villagers from one house to another.) Anyway, when I delete the building, the software "remembers" all the beds and the previous occupants. I know this because when I readd the building to the map, all the previous villagers are still residents.

**Comment by Luke100000** [comment]
Counting towards max population is fine, because they are still valid beds which you may assign manually.
When you destroy a bed you wont see the effect immediately on the blueprint, because the villagers only realize that when they try to sleep.
In 7.4.1 (to be uploaded anytime soon) I fixed a bunch of errors related to restricted buildings, set home and similar. You may need to destroy and replace the beds to reset the state. Please report if it still behaves wrong.

**Comment by Wilevar** [comment]
I'll check once the new version is up and see how it's working.
In my case, breaking down a bed _does_ result in an immediate change in the villager max population count.

I had 6 beds in standard buildings, and 3 beds in a restricted building I was living in, resulting in a max population of 9.
I was under the impression that making a building "restricted" would prevent villagers from trying to sleep in the beds there in.

The reason I feel they shouldn't count toward the max population is because if that's "my house" and the beds are never assigned to any villagers, I then have 3 villagers that are permanently homeless. If I make more houses, add more beds, then the population max increases, and soon more homeless villagers will be born/move in to fill the population, but they won't have beds.

So in my mind, if a building being restricted means "Villagers won't move in" then the beds in a restricted building shouldn't count toward the max population.
