### ISSUE TITLE
homosexuality and bisexuality are compatible

### ISSUE THREAD

**Issue by macarango** [Luke100000/minecraft-comes-alive#576]
**Is your feature request related to a problem? Please describe.**
i choose homosexuality as a trait and found out that people without that trait cant be with you i thought that bisexual people would be possible to marry but for some reason it isnt

**Describe the solution you'd like**
homosexuality and bisexuality are able to get togheter aslong as they are the same gender they shouldnt have to have the homosexuality trait if they already have bisexulaity

**Comment by ghost** [comment]
@Luke100000 
> https://github.com/Luke100000/minecraft-comes-alive/issues/534

That's not the issue, that one is about having both the homosexual and bisexual trait.
The issue at hand is that for some reason players/villagers with the homosexual trait cannot marry villagers with the bisexual trait even if they're both the same gender, basically making it so that bisexuals can only date other bisexuals or a non-homosexual villager of the opposite gender.

Also this should 100% be tagged as a bug, not an enhancement.

**Comment by Luke100000** [comment]
Both issues are caused by the same broken code, if I fix one, the other issue would have been fixed too. Hopefully.

**Comment by ghost** [comment]
Alright, thanks for the quick response.
