### ISSUE TITLE
Villagers - Blueprint

### ISSUE THREAD

**Issue by FridaysGirl2001** [Luke100000/minecraft-comes-alive#597]
Hello, 

On my blueprint, there are several villagers on my list that do not live in my village, and I cannot find them anywhere. They all were visitors at my inn at one time that I interacted with. I didn’t ask any of them to stay, but they stay on the list, taking up slots for actual villagers.

None of their names have popped up on any gravestones either, so I don’t think they’re dead. 

I have repaired and updated my mods and I don’t think it’s the game. I only have Architectury and MCA downloaded. 

Is there a way to fix this? Thank you in advance

**Comment by Luke100000** [comment]
Fixed in 7.5.6 and those who already assigned themselves before that version should get fixed in a future version.
You can `/mca-admin deleteVillage villageName` to force reset the list if you want. The list barely has an effect on gameplay tho.
Will merge this with https://github.com/Luke100000/minecraft-comes-alive/issues/586 :)
