### ISSUE TITLE
Many bugs associated with character creation and village generation

### ISSUE THREAD

**Issue by SimplyTadpole** [Luke100000/minecraft-comes-alive#599]
## **Describe the bug**
It seems that MCA's new character creation feature seems to be rather buggy, presenting many different problems. The three biggest issues I've personally experienced were:

• **1.:** There is an *enormous* (over ~15 minutes) delay when selecting your origin/spawn point for you to actually be teleported there; until then, you will be stuck in a mostly-random location (likely the default world spawn point?) where time will constantly be reverting to 6:30 AM and nearly every mob will be frozen in place, and you'll be nearly unable to interact with anything.
• **2.:** When you *do* arrive in a village, it has a high chance to not generate any villagers at all.
• **3.:** If you choose to use a MCA skin model, it will work flawlessy while the game's still stuck in the ~15-minute delay where everything's frozen, but once you finally get teleported to a village, your playermodel will break and become a hybrid fusion between your default Minecraft skin and the MCA skin you chose.

I saved a screenshot of the last two bugs to show them in action in the screenshot category below. (Obviously the first bug can't be shown with a screenshot, and it's too long to record a video of)

## **To Reproduce**
• **1.:** Create a world
• **2.:** Select a MCA skin and player model instead of using the vanilla model/skin
• **3.:** Choose to start in a village
• **4.:** Witness the extreme lag and failed villager/player model generation

## **Screenshots**
![minecraft bug](https://user-images.githubusercontent.com/70490001/221376398-e6b24bc6-9e05-45e9-a232-5a945a3e13ff.png)

Notice how there are weird green streaks throughout my character's head and torso, as well as a slight blue one in their chest; those are from my Minecraft skin, clipping through the MCA skin which otherwise looks normal. Also notice the existence of Rat mobs in the minimap in the top-left corner; those are from the Rat's Mischief mod, and they only spawn when a village is completely devoid of inhabitants, hinting at how the MCA villagers failed to spawn entirely.

## **Version**
- **MCA Version:** 7.4.6
- **Minecraft version:** 1.19.2
- **Modloader:** Quilt

## **Latest.log**
I hope this is the right one, there are a LOT of logs in there. Oops...
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/10832182/latest.log)

**Comment by Luke100000** [comment]
1) That means it finally works! Previously it just resulted in a timeout ^^ No srsly, the issue is that the teleportation needs to find a valid spawn point, right? But for whatever reason, for some people it is veeeery slow (notice I'm using vanilla stuff here).
2) https://github.com/Luke100000/minecraft-comes-alive/issues/594 my fault, fixed soon
3) Looks like a mod incompatibility, is it 3D skins mod? If you are bored, can you test the previous version, which btw fixes bug 2 too.
Thanks for that very detailed bug report!

**Comment by SimplyTadpole** [comment]
Ah, makes sense regarding villager teleportation ^^' I hope it's possible to find another method that's easier and faster for the engine to work with, in the meantime I think there should likely either be a warning saying that the village teleportation may take a long time to work, or hide the menu altogether by default (which is what I did on the config file, lol).

As for the skins, turns out it indeed was the 3d Skin Layers mod causing the issue; removing it fixed it. Is it a known incompatibility problem? Can it be fixed on the MCA side, would I have to ask the maintainer of that mod to implement compatibility, or is there no way for these two mods to work together? Either way, thanks for pointing it out to me. ^^'

Glad to know the issue with villagers not spawning will be fixed soon ^^' And yes, reverting to the previous version made villagers spawn properly! Any possibilities of there being a hotfix being uploaded ASAP? It's kind of a pretty major issue :sweat_smile:

**Comment by Luke100000** [comment]
Regarding 1) I would need to rewrite the code myself. Which is risky ^^
Regarding the 3D skin, I'm not aware of an issue but apparently there is one. Will see if I can fix that.
Yes, a hotfix is on the way, probably being uploaded today.

**Comment by D3SL** [comment]
Glad I found this, I'm having the same issue. MCA is basically unplayable for me because of how badly it hangs the server process. I can't even save and quit, it just stays stuck permanently, I have to actually kill minecraft from multiMC. The bright side is choosing "somewhere" as a spawn option completely moots the issue, the downside is no villagers are spawning anymore.

[edit]

So I did manage to find some villages that weren't ghost towns. I'm wondering if there's some kind of interaction going on with CTOV

**Comment by Luke100000** [comment]
The initial lag is a vanilla issue. To find a village it needs to generate a world first, which may end up loading a 5k by 5k world. Especially on shared servers quite a load.

No idea about the ghost towns. It seems like a mod compat but I can not think about a case where villagers would disappear.

**Comment by D3SL** [comment]
My guess was mod compat too since I did eventually find some quite crowded villages. The initial lag thing though is weird. I _thought_ I'd beaten it by picking "somewhere" as a spawn instead of a village but this last world gen it still had the same problem.

As for the lag I can understand maybe a couple minutes to generate enough biomes to get a matching selection (assuming someone didn't pick "somewhere"), but this last time not only did I pick "somewhere" I also left minecraft running for over half an hour.

I think there's something else going on under the hood because I've got a pretty beefy processor and can easily generate a massive world way faster than this. Particularly since my log gets flooded with stack traces about java workers getting hung up and server tics taking astronomical amounts of time. [Here's a sample](https://paste.ee/p/vWln0). This goes on for six solid megabytes of log file.

I'm wondering if it's either modernfix, smoothchunks, or both that might be behind this. I can't debug further tonight but I'm going to try without smoothchunks tomorrow and then if that still has a conniption fit I'll drop modernfix next.

**Comment by D3SL** [comment]
I've been messing with this for a bit now and it _seems_ like either fastload or smooth chunk saving was the issue. I think what was happening was MCA:R was running its initial search for a chunk to teleport/spawn the player to while the other mods were preventing or limiting its ability to do that, and the two/three wound up fighting over chunk loading each and every tick.
