### ISSUE TITLE
suggestion about ai membership

### ISSUE THREAD

**Issue by SniffSniff125** [Luke100000/minecraft-comes-alive#673]
**Is your feature request related to a problem? Please describe.**
expanding the ai limit costs every month, it almost transforms minecraft in a pay for feature game

**Describe the solution you'd like**
i would like an option to use the pc's processing power instead of a server's
it could decrease fps, but many players have a decent hardware
**Describe alternatives you've considered**
a one time membership or a site to watch ads instead of paying, for example: 10 ads for 2 days

**Additional context**
minecraft is played by people of all ages , not everyone is allowed / can afford to pay a monthly membership

have a nice day/night

**Comment by Luke100000** [comment]
To run an equivalent AI without hacking around you would need a GPU with around 32 GB VRAM (which is much more than a RTX 4090). Players would also need to download around 50 GB of data. It's safe to say that current gen hardware is not suitable to run that yet, but we will get there eventually.

Lower tier models performed horrible, it was funnier to talk with my cat.

I despise ads and will never add an ad based funding.

I understand that people can't get a membership, that's why I allow free interactions per hour, which I pay for.

**Comment by Luke100000** [comment]
I keep this issue open for potential further plans. One solution might be https://horde.koboldai.net/
It performs worse than OpenAI imo and is much slower in terms of response time, but could serve as a free mode. But since the horde is crowdsourced we need a way to contribute back to it, e.g. using Stable Diffusion workers.

**Comment by Luke100000** [comment]
Merged with #798
