### ISSUE TITLE
Using the "moddedVillagerWhitelist" option

### ISSUE THREAD

**Issue by Kpxxpkk** [Luke100000/minecraft-comes-alive#960]
Okay, with a 99% probability I simply cannot specify the syntax correctly, but it seems that the "moddedVillagerWhitelist" option does not work normally.
I'm trying to ennoble the guards from the guard-villagers mod
[](https://www.curseforge.com/minecraft/mc-mods/guard-villagers )(as an example).
I tried to specify this mob in several options:
at first as
```
"moddedVillagerWhitelist": [
    "#guardvillagers:guard"
  ],
```
then
```
 "moddedVillagerWhitelist": [
    "guardvillagers:guard"
  ],
```
and finally
```
"moddedVillagerWhitelist": [
    "guardvillagers.guard"
  ],
```
After each change in the configs, I first tried to update the guards on the existing map through the command, and then created a new map and checked it the same way on it. But squidwardism is incurable.
Please tell me what I'm doing wrong.

**Comment by Luke100000** [comment]
Entities needs to extend from villager so convert, but guards are technically not villagers. I added more explanation to the config wiki page. Realistically, that config option is quite useless, its only used in rare examples where a mod extends from villager, but only adds neglectable features (animations, custom model, ...) but is otherwise convertable to a vanilla/mca one.
