### ISSUE TITLE
Too many dark skin villager

### ISSUE THREAD

**Issue by SakuraRK** [Luke100000/minecraft-comes-alive#971]
Why are the new MCA villagers and players random skins basically dark colours how?
While I admit I'm a person of colour(I'm China people), most people of colour aren't dark skinned, even subtropical and tropical Indians and even East Asians don't have that many dark skinned ones.
Not to mention most villages are on the plains, how can humans in a temperate plains climate be dark skinned?

**Comment by Luke100000** [comment]
Skin color is based on temperature. Apparantly its hot where you are (plains have a above average base temp).

**Comment by NcrRanger90** [comment]
I agree that it makes no sense. Since the point of the mod is to make the game feel more alive, by making villagers feel and look more human,  the fact that almost every villager in a plains biome is dark skinned, does hurt the immersion a little bit.   And it's because irl, people who live in temperate climates, which is what the plains biome is, don't look like that. The desert and the savannah make complete sense. But the plains and even the taiga? because even in the taiga biome, there's some skin color variation.
Not a big deal for me tho. It just slightly breaks the immersion sometimes.

**Comment by Luke100000** [comment]
I will double check the curve. The problem is, that temperature in MInecraft is a bit of a magic number. It does not always make sense, nor is it always linear. Maybe I just messed up the math. Or, maybe its a mod conflict, changing the values. So many possibilities ^^

Adding a mapping is what I would like to avoid, for the sake of mod compatibility.

**Comment by SakuraRK** [comment]
> I will double check the curve. The problem is, that temperature in MInecraft is a bit of a magic number. It does not always make sense, nor is it always linear. Maybe I just messed up the math. Or, maybe its a mod conflict, changing the values. So many possibilities ^^
> 
> Adding a mapping is what I would like to avoid, for the sake of mod compatibility.
----
> I think we can add second skin color map, And player can change to another one/custom by theyself? @_@

**Comment by Luke100000** [comment]
That's a resourcepack, you can do that anytime :)
